In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [6]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]


In [17]:
A = np.array([[1,2,3],
              [4,5,6]])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [43]:
A = np.array([1,2,3])

#Same as np.ndim()
print(np.linalg.matrix_rank(A))

1


In [28]:
A = np.array([[1,2],
              [3,4]])

#Sum of Top-Left and Bottom-Right elements
print(np.linalg.trace(A))

5


In [30]:
#2x + y = ?
#x - y = ?
A = np.array([[2,1],
              [1,-1]])

# = 5
# = 1
B = np.array([5,1])

solution = np.linalg.solve(A,B)

print(solution)

[2. 1.]


In [37]:
arr = np.arange(1, 10)

print(arr)

new = arr.reshape(3, 3)

print(new)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
arr = np.array([1,2,3,4])

print(np.resize(arr,(2,3)))


[[1 2 3]
 [4 1 2]]


In [42]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [46]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(np.vstack((a, b)))

print(np.column_stack((a,b)))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [6]:
arr = np.array([10,20,30,40,50])

print(np.percentile(arr,25))
print(np.percentile(arr,50))
print(np.percentile(arr,75))
print(np.percentile(arr, 100))

20.0
30.0
40.0
50.0


In [15]:
print(np.random.randint(1,10,size=5))

[5 5 8 1 4]


In [20]:
print(np.random.rand(5))

[0.85450296 0.59932153 0.24095194 0.33495319 0.57932731]


In [23]:
print(np.random.rand(3, 3, 3))

[[[0.42700431 0.61249007 0.57750734]
  [0.14979843 0.10820875 0.59651916]
  [0.50237442 0.10220432 0.88182892]]

 [[0.17103949 0.55576433 0.97076789]
  [0.98722985 0.2497484  0.25194881]
  [0.50003883 0.81385012 0.33631586]]

 [[0.74987392 0.51488708 0.56004452]
  [0.15190995 0.02717403 0.36282544]
  [0.92119629 0.36241117 0.59605466]]]


In [15]:
colors = ["Red","Blue","Green"]

print(np.random.choice(colors, p=[0.2,0.3,0.5]))

Green


In [22]:
np.random.seed(41)

print(np.random.randint(1,100,5))

[65 36 13 99 81]


In [18]:
np.random.randint(1, 10, 5)

array([9, 1, 9, 5, 7], dtype=int32)

In [19]:
np.random.rand(5)

array([0.50969724, 0.54780187, 0.33208673, 0.08140639, 0.79793332])

In [20]:
np.random.randn(5)

array([-1.03292327,  1.0108637 ,  0.43133832,  0.63432753,  1.76212298])

In [23]:
arr = np.arange(10)

print(arr)

np.random.shuffle(arr)

print(arr)

[0 1 2 3 4 5 6 7 8 9]
[2 8 7 1 9 6 4 0 3 5]


In [3]:
arr = np.array([[1,2],
                [3,4]])

print(arr.ravel())

[1 2 3 4]
