In [9]:
import numpy as np


x = np.array([[1, 3, 4], 
              [5,6, 7],
             [9, 1, 7]])

y = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])


print(x @ y)

[[1 3 4]
 [5 6 7]
 [9 1 7]]


In [1]:
#Note: In this week review he mainly focus on asking question as deep as possible not practicles at all 
#Reveiwer: OR230 (Male)